// <auto-generated />
namespace Scoring3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addFieldRequiestAmountToOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFieldRequiestAmountToOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202105311902041_addFieldRequiestAmountToOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
